#!/bin/sh

#date '+%Y %b %d (%a) %I:%M%p'
#date '+%d/%m/%y (%a) %I:%M %p'

date '+%a, %m/%d/%y %I:%M %p'

#ICON='/usr/share/icons/Mint-Y/status/16/info.png'
# -i $ICON

case $BLOCK_BUTTON in
	1) pgrep -x dunst >/dev/null && notify-send "This Month " "$(cal -m --color=always | sed "s/..7m/<b><span color=\"red\">/;s/..27m/<\/span><\/b>/")" && notify-send "Appointments" "$(calcurse -D ~/.config/calcurse -d5)" ;;
	2) "$TERMINAL" -e calcurse -D ~/.config/calcurse ;;
	3) pgrep -x dunst >/dev/null && notify-send "📅 Time/date module" "\- Left click to show upcoming appointments for the next three days via \`calcurse -d3\` and show the month via \`cal\`
- Middle click opens calcurse if installed" ;;
esac
