#!/bin/sh

docker_status() {
    OUTPUT=$(systemctl status docker.service | grep "(running)")
    if echo "$OUTPUT" | grep -q "(running)"; then
        ICON="🐳"
    else
        ICON="🐨"
    fi

    printf "%s\n" $ICON 
}


 docker_status

case $BLOCK_BUTTON in
    1) docker_status ;; 
esac; exit




#case $BLOCK_BUTTON in
#	1) mpc status | filter && setsid "$TERMINAL" -e ncmpcpp & ;;  # right click, pause/unpause
#	2) mpc toggle | filter ;;  # right click, pause/unpause
#	3) mpc status | filter && pgrep -x dunst >/dev/null && notify-send "🎵 Music module" "\- Shows mpd song playing.
#	- Italic when paused.
#	- Left click opens ncmpcpp.
#	- Middle click pauses.
#	- Scroll changes track.";;  # right click, pause/unpause
#	4) mpc prev   | filter ;;  # scroll up, previous
#	5) mpc next   | filter ;;  # scroll down, next
#	*) mpc status | filter ;;
#esac; exit
