#!/bin/bash

docker_status() {
    OUTPUT=$(systemctl status docker.service | grep "(running)")
    if echo "$OUTPUT" | grep -q "(running)"; then
        ICON="🐳"
    else
        ICON="🐨"
    fi

    printf "%s\n" $ICON
}

 docker_status

case $BLOCK_BUTTON in
    1) docker=$(systemctl is-active docker)
    if [ "$docker" == "active" ]
    then
        sudo systemctl stop docker.service && notify-send "Docker service" "🐨 Stoping.."
    else
        sudo systemctl start docker.service && notify-send "Docker service" "🐳 Starting.."
    fi
    ;;
    3) notify-send "Docker service" "🐨 Left click for Docker servce start
🐳 Right click for Docker service
    ";;
esac; exit
