#!/usr/bin/env python3
import requests

r = requests.get('https://www.cbr-xml-daily.ru/daily_json.js')

if r.status_code == 200:
    try:
        data = r.json()
    except ValueError:
        data = 0
else:
    print(r.status_code)

print (round(data['Valute']['USD']['Value'], 2))
